name: kooshy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  geolocator: ^8.2.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  blur: ^3.1.0
  audioplayers: ^0.20.1
  firebase_core: ^1.17.0
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.15
  swipe: ^0.0.1
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  icons_launcher: ^1.1.8
flutter_icons:
  image_path: 'acssets/images/logoSplashScreen/iconKooshy.png'
  ios: true
  android: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # The following section is specific to Flutter.
  generate: true # Add this line

  # To add assets to your application, add an assets section, like this:
  assets:
     - acssets/images/background/backgroundNight.jpg
     - acssets/images/background/backgroundinfo.jpg
     - acssets/images/background/backgroundsetting.jpg
     - acssets/iconAnimation/circleBlack.json
     - acssets/iconAnimation/circleWhite.json
     - acssets/iconAnimation/cloud.json
     - acssets/iconAnimation/cloudMoonMin.json
     - acssets/iconAnimation/cloudSunnyMin.json
     - acssets/iconAnimation/cloudThunder.json
     - acssets/iconAnimation/errorCat.json
     - acssets/iconAnimation/loaddingSlime.json
     - acssets/iconAnimation/mist.json
     - acssets/iconAnimation/moon.json
     - acssets/iconAnimation/moonRain.json
     - acssets/iconAnimation/snowCloud.json
     - acssets/iconAnimation/snowMoon.json
     - acssets/iconAnimation/snowSunny.json
     - acssets/iconAnimation/storm.json
     - acssets/iconAnimation/sunny.json
     - acssets/iconAnimation/sunnyMist.json
     - acssets/iconAnimation/sunnyRain.json
     - acssets/iconAnimation/sunnyStorm.json
     - acssets/images/logoSplashScreen/logovqhapps.png
     - acssets/images/introScreen/logoKooshy.png
     - acssets/images/introScreen/introKooshy2.png
     - acssets/images/introScreen/introKooshy3.png
     - acssets/images/logoSplashScreen/iconKooshy.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: ChakraPetch
       fonts:
         - asset: acssets/fonts/ChakraPetch-Regular.ttf
         - asset: acssets/fonts/ChakraPetch-Italic.ttf
           style: italic
         - asset: acssets/fonts/ChakraPetch-Light.ttf
           weight: 100
         - asset: acssets/fonts/ChakraPetch-Bold.ttf
           weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
