import 'package:equatable/equatable.dart';

import '../Models/weather.dart';

abstract class WeatherState extends Equatable{
  const WeatherState();
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();

}
class WeatherStateInitial extends WeatherState{}
class WeatherStateLoading extends WeatherState{}
class WeatherStateSuccess extends WeatherState{
   final WeatherMain autogeneratedWeather;
  const WeatherStateSuccess({required this.autogeneratedWeather});
   @override
   // TODO: implement props
   List<Object?> get props => [autogeneratedWeather];
}
class WeatherStateFail extends WeatherState{}